-- 9.27 Class Hub - Supabase setup
-- Run this ONCE in Supabase SQL Editor.
-- Do NOT put a service_role/secret key in the website.

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  stt integer not null unique,
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.scores (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  subject text not null,
  score numeric(4,2) not null check (score >= 0 and score <= 10),
  created_at timestamptz not null default now()
);

create table if not exists public.violations (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students(id) on delete cascade,
  violation_date date,
  description text not null,
  penalty numeric(5,2) not null default 0,
  week_label text,
  created_at timestamptz not null default now()
);

create index if not exists scores_student_id_idx on public.scores(student_id);
create index if not exists violations_student_id_idx on public.violations(student_id);

alter table public.students enable row level security;
alter table public.scores enable row level security;
alter table public.violations enable row level security;

-- Admin identity is the email you create in Authentication > Users.
create or replace function public.is_class_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((auth.jwt() ->> 'email') = 'admin@9-27.local', false);
$$;

-- Re-runnable policies: remove only policies owned by this setup.
drop policy if exists "students_public_read" on public.students;
drop policy if exists "students_admin_write" on public.students;
drop policy if exists "scores_public_read" on public.scores;
drop policy if exists "scores_admin_write" on public.scores;
drop policy if exists "violations_public_read" on public.violations;
drop policy if exists "violations_admin_write" on public.violations;

create policy "students_public_read"
on public.students for select
using (true);

create policy "students_admin_write"
on public.students for all
using (public.is_class_admin())
with check (public.is_class_admin());

create policy "scores_public_read"
on public.scores for select
using (true);

create policy "scores_admin_write"
on public.scores for all
using (public.is_class_admin())
with check (public.is_class_admin());

create policy "violations_public_read"
on public.violations for select
using (true);

create policy "violations_admin_write"
on public.violations for all
using (public.is_class_admin())
with check (public.is_class_admin());

-- Seed the 46 existing students. Safe to run more than once.
insert into public.students (stt, name) values
(1,'Bùi Thị Hoài An'),(2,'Nguyễn Gia Bảo'),(3,'Ngô Thanh Bình'),(4,'Nguyễn Hoàng Bảo Châu'),
(5,'Nguyễn Phạm Khánh Chi'),(6,'Trần Uy Dũng'),(7,'Phan Đức Duy'),(8,'Nguyễn Minh Đăng'),
(9,'Phạm Huỳnh Trường Giang'),(10,'Nguyễn Lê Gia Hào'),(11,'Đặng Phạm Gia Hân'),(12,'Nguyễn Thu Hiền'),
(13,'Phùng Bá Hiệp'),(14,'Nguyễn Minh Hữu'),(15,'Bùi Minh Khang'),(16,'Đặng Nguyễn Ngọc Khánh'),
(17,'Nguyễn Bá Khôi'),(18,'Nguyễn Trung Kiên'),(19,'Nguyễn Bá Kiệt'),(20,'Đào Huỳnh Bảo Lâm'),
(21,'Nguyễn Hải Lân'),(22,'Nguyễn Lê Mai'),(23,'Phan Nguyễn Ngọc Mai'),(24,'Lữ Triều Minh'),
(25,'Nguyễn Phạm Bảo Minh'),(26,'Lê Hồng Ngọc'),(27,'Hồ Hữu Khôi Nguyên'),(28,'Hoàng Gia Nguyễn'),
(29,'Phan Thiện Nhân'),(30,'Nguyễn Thị Ngọc Nhi'),(31,'Nguyễn Yến Nhi'),(32,'Nguyễn Kim Oanh'),
(33,'Nguyễn Đăng Phong'),(34,'Hoàng Nhật Quang'),(35,'Hoàng Lê Như Quỳnh'),(36,'Võ Đức Tài'),
(37,'Nguyễn Hoàng Phương Thảo'),(38,'Phạm Anh Thư'),(39,'Nguyễn Đức Toàn'),(40,'Trần Thị Minh Trang'),
(41,'Nguyễn Hoàng Thiên Trí'),(42,'Huỳnh Lê Thủy Trúc'),(43,'Phan Cẩm Vi'),(44,'Trần Quang Vinh'),
(45,'Phạm Đăng Vương'),(46,'Nguyễn Thị Yến Vy')
on conflict (stt) do update set name = excluded.name;
