-- 9.27 Class Hub - online seat plan migration
-- Run this ONCE after supabase-setup.sql. It is safe to run again.

create table if not exists public.seat_assignments (
  id bigint generated by default as identity primary key,
  row_no integer not null check (row_no between 1 and 6),
  col_no integer not null check (col_no between 1 and 8),
  student_id bigint not null references public.students(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(row_no, col_no),
  unique(student_id)
);

create index if not exists seat_assignments_student_id_idx on public.seat_assignments(student_id);

alter table public.seat_assignments enable row level security;
drop policy if exists "seat_public_read" on public.seat_assignments;
drop policy if exists "seat_admin_write" on public.seat_assignments;

create policy "seat_public_read"
on public.seat_assignments for select
using (true);

create policy "seat_admin_write"
on public.seat_assignments for all
using (public.is_class_admin())
with check (public.is_class_admin());

-- Import the current 6x8 arrangement from data.js.
insert into public.seat_assignments (row_no,col_no,student_id)
select v.row_no, v.col_no, s.id
from (values
(1,1,'Phạm Anh Thư'),(1,2,'Nguyễn Lê Gia Hào'),(1,3,'Trần Thị Minh Trang'),(1,4,'Phạm Huỳnh Trường Giang'),(1,5,'Nguyễn Gia Bảo'),(1,6,'Phan Thiện Nhân'),(1,7,'Hoàng Lê Như Quỳnh'),(1,8,'Nguyễn Bá Khôi'),
(2,1,'Nguyễn Minh Hữu'),(2,2,'Ngô Thanh Bình'),(2,3,'Hồ Hữu Khôi Nguyên'),(2,4,'Nguyễn Hoàng Phương Thảo'),(2,5,'Phan Đức Duy'),(2,6,'Nguyễn Thu Hiền'),(2,7,'Nguyễn Phạm Khánh Chi'),(2,8,'Nguyễn Đăng Phong'),
(3,1,'Phạm Đăng Vương'),(3,2,'Bùi Thị Hoài An'),(3,3,'Nguyễn Trung Kiên'),(3,4,'Lê Hồng Ngọc'),(3,5,'Trần Uy Dũng'),(3,6,'Nguyễn Hoàng Bảo Châu'),(3,7,'Nguyễn Minh Đăng'),(3,8,'Đặng Phạm Gia Hân'),
(4,1,'Phan Nguyễn Ngọc Mai'),(4,2,'Nguyễn Hải Lân'),(4,3,'Nguyễn Lê Mai'),(4,4,'Nguyễn Hoàng Thiên Trí'),(4,5,'Nguyễn Phạm Bảo Minh'),(4,6,'Phan Cẩm Vi'),(4,7,'Đặng Nguyễn Ngọc Khánh'),
(5,1,'Nguyễn Đức Toàn'),(5,2,'Phùng Bá Hiệp'),(5,3,'Võ Đức Tài'),(5,4,'Nguyễn Thị Yến Vy'),(5,5,'Nguyễn Thị Ngọc Nhi'),(5,6,'Hoàng Nhật Quang'),(5,7,'Trần Quang Vinh'),(5,8,'Huỳnh Lê Thủy Trúc'),
(6,2,'Hoàng Gia Nguyễn'),(6,3,'Lữ Triều Minh'),(6,4,'Nguyễn Kim Oanh'),(6,5,'Nguyễn Bá Kiệt'),(6,6,'Đào Huỳnh Bảo Lâm'),(6,7,'Nguyễn Yến Nhi'),(6,8,'Bùi Minh Khang')
) as v(row_no,col_no,name)
join public.students s on s.name=v.name
on conflict (row_no,col_no) do nothing;
