-- BÀI TẬP + TRỰC NHẬT ONLINE CHO 9.27 CLASS HUB
-- Chạy sau supabase-setup.sql (và supabase-seat-plan.sql nếu đang dùng chỗ ngồi).

create table if not exists public.homework (
  id bigint generated by default as identity primary key,
  homework_date date not null,
  subject text not null,
  icon text not null default '📚',
  description text not null,
  created_at timestamptz not null default now()
);

create index if not exists homework_date_idx on public.homework(homework_date desc, created_at desc);

create table if not exists public.duty_schedule (
  id bigint generated by default as identity primary key,
  week_start date not null unique,
  group_name text not null,
  members text not null,
  created_at timestamptz not null default now()
);

create index if not exists duty_week_start_idx on public.duty_schedule(week_start desc);

alter table public.homework enable row level security;
alter table public.duty_schedule enable row level security;

drop policy if exists "homework_public_read" on public.homework;
create policy "homework_public_read" on public.homework for select using (true);

drop policy if exists "homework_admin_all" on public.homework;
create policy "homework_admin_all" on public.homework for all using (public.is_class_admin()) with check (public.is_class_admin());

drop policy if exists "duty_public_read" on public.duty_schedule;
create policy "duty_public_read" on public.duty_schedule for select using (true);

drop policy if exists "duty_admin_all" on public.duty_schedule;
create policy "duty_admin_all" on public.duty_schedule for all using (public.is_class_admin()) with check (public.is_class_admin());

-- Nếu muốn giữ bài tập cũ trong data.js, có thể nhập thủ công sau khi tạo bảng.
